Repository AY2223S1-CS2113-T18-2/tp, pull requests merged in 2022-10, with the labels that each got.

#14 Fix I/O redirection test
  build.gradle
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task

#15 add Add command
  .gitignore
  src/main/java/recipeditor/command/AddCommand.java
  src/main/java/recipeditor/command/Command.java
  src/main/java/recipeditor/command/InvalidCommand.java
  src/main/java/recipeditor/parser/Parser.java
  src/main/java/recipeditor/recipe/Ingredient.java
  src/main/java/recipeditor/recipe/Recipe.java
  src/main/java/recipeditor/ui/AddMode.java
  src/main/java/recipeditor/ui/Ui.java
Labels: priority.High, type.Story

#13 Parse bye, add, delete and list commands
  src/main/java/recipeditor/Recipeditor.java
  src/main/java/recipeditor/command/AddCommand.java
  src/main/java/recipeditor/command/ByeCommand.java
  src/main/java/recipeditor/command/Command.java
  src/main/java/recipeditor/command/DeleteCommand.java
  src/main/java/recipeditor/command/ListCommand.java
  src/main/java/recipeditor/parser/Parser.java
Labels: type.Task, priority.High

#40 JUnit Testing
  src/main/java/recipeditor/Recipeditor.java
  src/main/java/recipeditor/command/Command.java
  src/main/java/recipeditor/command/CommandResult.java
  src/main/java/recipeditor/command/DeleteCommand.java
  src/main/java/recipeditor/parser/Parser.java
  src/main/java/recipeditor/recipe/Ingredient.java
  src/main/java/recipeditor/recipe/Recipe.java
  src/main/java/recipeditor/recipe/RecipeList.java
  src/main/java/recipeditor/storage/Storage.java
  src/main/java/recipeditor/ui/AddMode.java
  src/main/java/recipeditor/ui/Ui.java
  src/test/java/recipeditor/command/CommandResultTest.java
  src/test/java/recipeditor/command/parser/ParserTest.java
  src/test/java/recipeditor/parser/ParserTest.java
  src/test/java/recipeditor/ui/UiTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#39 Storage save data
  src/main/java/recipeditor/recipe/Ingredient.java
Labels: type.Task, priority.High

#56 Storage and UI Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/recipeditor/ui/AddMode.java
  src/main/java/recipeditor/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#59 Find command
  data/data.txt
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/recipeditor/command/AddCommand.java
  src/main/java/recipeditor/command/CommandResult.java
  src/main/java/recipeditor/command/DeleteCommand.java
  src/main/java/recipeditor/command/EditCommand.java
  src/main/java/recipeditor/command/ExitCommand.java
  src/main/java/recipeditor/command/FindCommand.java
  src/main/java/recipeditor/command/InvalidCommand.java
  src/main/java/recipeditor/command/ListCommand.java
  src/main/java/recipeditor/command/ViewCommand.java
  src/main/java/recipeditor/parser/Parser.java
  src/main/java/recipeditor/recipe/Recipe.java
  src/main/java/recipeditor/recipe/RecipeList.java
  src/main/java/recipeditor/storage/Storage.java
  src/main/java/recipeditor/ui/Ui.java
  src/test/java/recipeditor/command/parser/ParserTest.java
  src/test/java/recipeditor/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/data/data.txt
  text-ui-test/input.txt
Labels: type.Task, priority.High

#60 Updated Storage functions to be more dynamic
  data/data.txt
  src/main/java/recipeditor/Recipeditor.java
  src/main/java/recipeditor/command/AddCommand.java
  src/main/java/recipeditor/command/DeleteCommand.java
  src/main/java/recipeditor/storage/Storage.java
Labels: type.Task, priority.High

#61 Init edit mode
  data/data.txt
  src/main/java/recipeditor/command/EditCommand.java
  src/main/java/recipeditor/parser/Parser.java
  src/main/java/recipeditor/recipe/Recipe.java
  src/main/java/recipeditor/recipe/RecipeList.java
  src/main/java/recipeditor/storage/Storage.java
  src/main/java/recipeditor/ui/EditMode.java
  text-ui-test/data/data.txt
Labels: type.Task, priority.High

#63 Developer guide on Architecture and Command
  docs/DeveloperGuide.md
  docs/UML diagrams/Command.puml
  docs/UML diagrams/Main.puml
  docs/UML diagrams/Style.puml
  docs/images/CommandClassDiagram.png
  docs/images/MainClassDiagram.png
Labels: priority.High

#64 GUI Editor
  Storage/App/Temp.txt
  Storage/App/Template.txt
  build.gradle
  data/data.txt
  docs/README.md
  docs/Template.txt
  docs/UserGuide.md
  src/main/java/recipeditor/Recipeditor.java
  src/main/java/recipeditor/command/AddCommand.java
  src/main/java/recipeditor/exception/ParseFileException.java
  src/main/java/recipeditor/parser/Parser.java
  src/main/java/recipeditor/parser/TextFileParser.java
  src/main/java/recipeditor/storage/Storage.java
  src/main/java/recipeditor/ui/Editor.java
  src/main/java/recipeditor/ui/Ui.java
  src/test/java/recipeditor/RecipeditorTest.java
  src/test/java/recipeditor/parser/TextFileParserTest.java
  src/test/java/recipeditor/ui/EditorTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/Storage/App/Template.txt
Labels: type.Epic, priority.High, severity.High

#128 UG
  Storage/App/Template.txt
  docs/UserGuide.md
  docs/images/TextEditorWithTemplate.png
  src/main/java/recipeditor/storage/Storage.java
Labels: priority.High, type.Enhancement

#73 Updating storage to work with text files
  RecipeData/AllRecipes.txt
  RecipeData/App/Template.txt
  RecipeData/App/TemporaryFile.txt
  RecipeData/Recipes/SHEE
  data/data.txt
  src/main/java/recipeditor/Recipeditor.java
  src/main/java/recipeditor/command/AddCommand.java
  src/main/java/recipeditor/command/CommandResult.java
  src/main/java/recipeditor/command/DeleteCommand.java
  src/main/java/recipeditor/command/FindCommand.java
  src/main/java/recipeditor/command/HelpCommand.java
  src/main/java/recipeditor/command/ListCommand.java
  src/main/java/recipeditor/command/ViewCommand.java
  src/main/java/recipeditor/parser/Parser.java
  src/main/java/recipeditor/parser/TextFileParser.java
  src/main/java/recipeditor/recipe/Recipe.java
  src/main/java/recipeditor/recipe/RecipeList.java
  src/main/java/recipeditor/storage/Storage.java
  src/main/java/recipeditor/ui/Editor.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/RecipeData/AllRecipes.txt
  text-ui-test/RecipeData/App/Template.txt
Labels: type.Task, priority.High

#132 V2.1 User Guide
  RecipeData/AllRecipes.txt
  RecipeData/Recipes/Example Title
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ClassDiagrams/CommandClassDiagram.png
  docs/images/ClassDiagrams/MainClassDiagram.png
  docs/images/ClassDiagrams/StorageClassDiagram.png
  docs/images/ClassDiagrams/UiClassDiagram.png
  docs/images/UserGuide/ProgramStartScreen.png
  docs/images/UserGuide/TextEditorWithTemplate.png
  src/main/java/recipeditor/Recipeditor.java
  src/main/java/recipeditor/command/DeleteCommand.java
  src/main/java/recipeditor/command/HelpCommand.java
  src/main/java/recipeditor/recipe/Recipe.java
  src/main/java/recipeditor/storage/Storage.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#137 Show images in UG
  docs/UserGuide.md
Labels: type.Task, priority.Medium
