Repository AY2223S1-CS2113-T18-2/tp, pull requests merged in 2022-11, with the labels that each got.

#144 EditMode add changed
  src/main/java/recipeditor/edit/Add.java
Labels: priority.High, type.Story

#152 Update DG on Add Command
  docs/ClassDiagram/Command.puml
  docs/ClassDiagram/EditCommand.puml
  docs/ClassDiagram/Main.puml
  docs/ClassDiagram/RecipeModule.puml
  docs/ClassDiagram/StorageClassDiagram.puml
  docs/ClassDiagram/Style.puml
  docs/ClassDiagram/UiClassDiagram.puml
  docs/DeveloperGuide.md
  docs/diagrams/AddEditor.puml
  docs/diagrams/Architecture.puml
  docs/diagrams/Parse.puml
  docs/diagrams/Start.puml
  docs/images/SequenceDiagram/AddEditor.png
  docs/images/SequenceDiagram/Architecture.png
  docs/images/SequenceDiagram/Parse.png
  docs/images/SequenceDiagram/Start.png
Labels: type.Task, priority.High

#150 V2.1 fix bugs
  docs/UserGuide.md
  src/main/java/recipeditor/command/AddCommand.java
  src/main/java/recipeditor/command/DeleteCommand.java
  src/main/java/recipeditor/command/EditCommand.java
  src/main/java/recipeditor/command/HelpCommand.java
  src/main/java/recipeditor/command/InvalidCommand.java
  src/main/java/recipeditor/command/ViewCommand.java
  src/main/java/recipeditor/edit/Add.java
  src/main/java/recipeditor/exception/InvalidFlagException.java
  src/main/java/recipeditor/parser/Parser.java
  src/main/java/recipeditor/recipe/Recipe.java
Labels: priority.High, type.Bug, severity.High

#157 Update UG to address issues brought up
  docs/UserGuide.md
Labels: priority.Medium

#159 V2.1 JUnit testing
  src/main/java/recipeditor/command/DeleteCommand.java
  src/main/java/recipeditor/command/ViewCommand.java
  src/main/java/recipeditor/parser/Parser.java
  src/main/java/recipeditor/recipe/RecipeList.java
  src/test/java/recipeditor/command/HelpCommandTest.java
  src/test/java/recipeditor/parser/ParserTest.java
  src/test/java/recipeditor/storage/StorageTest.java
Labels: type.Task, priority.Medium

#162 Qian Hui's PPP
  docs/team/johndoe.md
  docs/team/qianz-z.md
Labels: type.Task, priority.Medium

#163 Update PPP
  docs/team/brominne.md
Labels: type.Task, priority.Medium

#166 /add and storage update
  docs/DeveloperGuide.md
  src/main/java/recipeditor/ui/Editor.java
Labels: priority.High

#164 V2.1 find command update
  docs/UserGuide.md
  src/main/java/recipeditor/command/EditCommand.java
  src/main/java/recipeditor/command/FindCommand.java
  src/main/java/recipeditor/command/InvalidCommand.java
  src/main/java/recipeditor/parser/FlagParser.java
  src/main/java/recipeditor/parser/Parser.java
  src/main/java/recipeditor/recipe/RecipeList.java
  src/test/java/recipeditor/command/CommandResultTest.java
  src/test/java/recipeditor/command/FindCommandTest.java
  src/test/java/recipeditor/command/HelpCommandTest.java
  src/test/java/recipeditor/command/parser/ParserTest.java
  src/test/java/recipeditor/parser/ParserTest.java
Labels: type.Task, priority.High

#172 JUnit test from Bian Rui Batch #1
  build.gradle
  src/main/java/recipeditor/command/DeleteCommand.java
  src/main/java/recipeditor/edit/Add.java
  src/main/java/recipeditor/edit/Delete.java
  src/main/java/recipeditor/edit/EditModeCommand.java
  src/main/java/recipeditor/exception/ParseException.java
  src/main/java/recipeditor/parser/FlagParser.java
  src/main/java/recipeditor/parser/Parser.java
  src/main/java/recipeditor/recipe/Ingredient.java
  src/main/java/recipeditor/storage/Storage.java
  src/test/java/recipeditor/command/AddCommandTest.java
  src/test/java/recipeditor/command/FindCommandTest.java
  src/test/java/recipeditor/command/ViewCommandTest.java
  src/test/java/recipeditor/edit/DeleteTest.java
  src/test/java/recipeditor/parser/FlagParserTest.java
  src/test/java/recipeditor/parser/ParseFileExceptionTest.java
  src/test/java/recipeditor/parser/ParserTest.java
  src/test/java/recipeditor/recipe/IngredientTest.java
Labels: type.Task, priority.Medium

#173 V2.1 minor updates
  docs/ClassDiagram/StorageClassDiagram.puml
  docs/ClassDiagram/Style.puml
  docs/ClassDiagram/UiClassDiagram.puml
  docs/DeveloperGuide.md
  docs/UML diagrams/Command.puml
  docs/UML diagrams/Main.puml
  docs/UML diagrams/Style.puml
  docs/diagrams/Architecture.puml
  docs/diagrams/Command.puml
  docs/diagrams/EditCommand.puml
  docs/diagrams/Main.puml
  docs/diagrams/RecipeModule.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/Style.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/Architecture.png
  docs/images/ClassDiagrams/StorageClassDiagram.png
  docs/images/ClassDiagrams/UiClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/team/qianz-z.md
  src/main/java/recipeditor/Recipeditor.java
  src/main/java/recipeditor/command/AddCommand.java
  src/main/java/recipeditor/command/DeleteCommand.java
  src/main/java/recipeditor/command/ExitCommand.java
  src/main/java/recipeditor/command/HelpCommand.java
  src/main/java/recipeditor/edit/Delete.java
  src/main/java/recipeditor/parser/Parser.java
  src/main/java/recipeditor/storage/Storage.java
  src/main/java/recipeditor/ui/Ui.java
  src/test/java/recipeditor/command/FindCommandTest.java
  src/test/java/recipeditor/command/HelpCommandTest.java
  src/test/java/recipeditor/command/ListCommandTest.java
  src/test/java/recipeditor/command/ViewCommandTest.java
  src/test/java/recipeditor/parser/ParserTest.java
  src/test/java/recipeditor/storage/StorageTest.java
Labels: type.Task, priority.Medium

#175 Added JUnit test for Add, GUI, ParseText to Recipe
  .gitignore
  docs/DeveloperGuide.md
  docs/SequenceDiagram/AddEditor.puml
  docs/SequenceDiagram/AddNewRecipeSequence.puml
  docs/SequenceDiagram/ExitStorageSequence.puml
  docs/SequenceDiagram/GUIComponent.puml
  docs/SequenceDiagram/ParseTextToRecipeSequence.puml
  docs/SequenceDiagram/StartupStorageSequence.puml
  docs/diagrams/GUIComponent.png
  docs/images/SequenceDiagram/ExitStorageSequence.png
  docs/images/SequenceDiagram/StartupStorageSequence.png
  docs/team/than-duc-huy.md
  src/main/java/recipeditor/Recipeditor.java
  src/main/java/recipeditor/command/ExitCommand.java
  src/main/java/recipeditor/parser/GuiWorkFlow.java
  src/main/java/recipeditor/parser/Parser.java
  src/main/java/recipeditor/parser/RecipeFileParser.java
  src/main/java/recipeditor/parser/TitleFileParser.java
  src/main/java/recipeditor/storage/Storage.java
  src/main/java/recipeditor/ui/Editor.java
  src/test/java/recipeditor/parser/GuiWorkFlowTest.java
  src/test/java/recipeditor/parser/ParserTest.java
  src/test/java/recipeditor/parser/ParserUtilsTest.java
  src/test/java/recipeditor/parser/RecipeFileParser.java
  src/test/java/recipeditor/parser/RecipeFileParserTest.java
  src/test/java/recipeditor/parser/TitleFileParserTest.java
  src/test/java/recipeditor/ui/EditorTest.java
Labels: priority.High

#190 update DG on DeleteCommand and ViewCommand Implementation
  docs/DeveloperGuide.md
  src/main/java/recipeditor/parser/Parser.java
Labels: type.Task, priority.High

#193 V2.1 resolve issues
  docs/UserGuide.md
  docs/diagrams/Main.puml
  docs/team/qianz-z.md
  src/main/java/recipeditor/command/AddCommand.java
  src/main/java/recipeditor/command/EditCommand.java
  src/main/java/recipeditor/command/ExitCommand.java
  src/main/java/recipeditor/command/FindCommand.java
  src/main/java/recipeditor/command/InvalidCommand.java
  src/main/java/recipeditor/command/ListCommand.java
  src/main/java/recipeditor/command/ViewCommand.java
  src/main/java/recipeditor/parser/FlagParser.java
  src/main/java/recipeditor/parser/GuiWorkFlow.java
  src/main/java/recipeditor/parser/Parser.java
  src/main/java/recipeditor/parser/ParserUtils.java
  src/main/java/recipeditor/parser/RecipeFileParser.java
  src/main/java/recipeditor/parser/TitleFileParser.java
  src/main/java/recipeditor/recipe/Recipe.java
  src/main/java/recipeditor/storage/Storage.java
  src/main/java/recipeditor/ui/Ui.java
  src/test/java/recipeditor/command/HelpCommandTest.java
  src/test/java/recipeditor/command/ViewCommandTest.java
  src/test/java/recipeditor/parser/ParserTest.java
Labels: priority.High, type.Bug

#196 V2.1 JUnit testing
  src/main/java/recipeditor/storage/Storage.java
  src/main/java/recipeditor/ui/Ui.java
  src/test/java/recipeditor/RecipeditorTest.java
  src/test/java/recipeditor/command/AddCommandTest.java
  src/test/java/recipeditor/command/CommandResultTest.java
  src/test/java/recipeditor/command/CommandTest.java
  src/test/java/recipeditor/command/DeleteCommandTest.java
  src/test/java/recipeditor/command/EditCommandTest.java
  src/test/java/recipeditor/command/ExitCommandTest.java
  src/test/java/recipeditor/command/FindCommandTest.java
  src/test/java/recipeditor/command/HelpCommandTest.java
  src/test/java/recipeditor/command/InvalidCommandTest.java
  src/test/java/recipeditor/command/ViewCommandTest.java
  src/test/java/recipeditor/edit/AddTest.java
  src/test/java/recipeditor/edit/ChangeTest.java
  src/test/java/recipeditor/edit/DeleteTest.java
  src/test/java/recipeditor/edit/EditModeCommandTest.java
  src/test/java/recipeditor/edit/SwapTest.java
  src/test/java/recipeditor/parser/FlagParserTest.java
  src/test/java/recipeditor/parser/GuiWorkFlowTest.java
  src/test/java/recipeditor/parser/ParserTest.java
  src/test/java/recipeditor/parser/ParserUtilsTest.java
  src/test/java/recipeditor/parser/RecipeFileParserTest.java
  src/test/java/recipeditor/parser/TitleFileParserTest.java
  src/test/java/recipeditor/recipe/IngredientTest.java
  src/test/java/recipeditor/recipe/RecipeListTest.java
  src/test/java/recipeditor/storage/StorageTest.java
Labels: type.Task, priority.Medium

#204 Standardise styling for UG
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#206 Change the styling of file path under data management
  docs/UserGuide.md
  src/main/java/recipeditor/parser/Parser.java
Labels: priority.Medium

#213 V2.1 JavaDocs
  src/main/java/recipeditor/Recipeditor.java
  src/main/java/recipeditor/command/InvalidCommand.java
  src/main/java/recipeditor/command/ListCommand.java
  src/main/java/recipeditor/edit/Change.java
  src/main/java/recipeditor/edit/Swap.java
  src/main/java/recipeditor/exception/ParseException.java
  src/main/java/recipeditor/exception/RecipeNotFoundException.java
  src/main/java/recipeditor/parser/FlagParser.java
  src/main/java/recipeditor/parser/Parser.java
  src/main/java/recipeditor/parser/TitleFileParser.java
  src/main/java/recipeditor/recipe/Ingredient.java
  src/main/java/recipeditor/recipe/Recipe.java
  src/main/java/recipeditor/recipe/RecipeList.java
  src/main/java/recipeditor/storage/Storage.java
  src/main/java/recipeditor/ui/Editor.java
  src/main/java/recipeditor/ui/GuiWorkFlow.java
Labels: type.Task, priority.High

#214 Removed magic numbers in recipe
  src/main/java/recipeditor/parser/RecipeFileParser.java
  src/main/java/recipeditor/recipe/Ingredient.java
Labels: priority.High
